/** @typedef {import("../data/constants").TLanguage} TLanguage */
/** @typedef {import("../data/constants").TInvoiceType} TInvoiceType */
/** @typedef {import("../data/constants").TCategoryType} TCategoryType */
/** @typedef {import("../data/constants").TItemType} TItemType */
/** @typedef {import("../data/constants").TUnit} TUnit */
/** @typedef {import("../data/constants").TInvoiceStatus} TInvoiceStatus */
/** @typedef {import("../data/constants").TKitchenOrderStatus} TKitchenOrderStatus */
/** @typedef {import("../data/constants").TKitchenOrderType} TKitchenOrderType */
/** @typedef {import("../data/constants").TDiscountType} TDiscountType */
/** @typedef {import("../data/constants").TTransactionEntityType} TTransactionEntityType */
/** @typedef {import("../data/constants").TTransactionReason} TTransactionReason */
/** @typedef {import("../data/constants").TTransactionStatus} TTransactionStatus */
/** @typedef {import("../data/constants").TVendorStatus} TVendorStatus */
/** @typedef {import("../data/constants").TSign} TSign */
/** @typedef {import("../data/constants").TTransferType} TTransferType */
/** @typedef {import("../data/constants").TTransferStatus} TTransferStatus */
/** @typedef {import("../data/constants").TUserStatus} TUserStatus */
/** @typedef {import("../data/constants").TWeekday} TWeekday */
/** @typedef {import("../data/constants").THolidayType} THolidayType */
/** @typedef {import("../data/constants").THolidayLeaveType} THolidayLeaveType */
/** @typedef {import("../data/constants").TAttendanceStatus} TAttendanceStatus */
/** @typedef {import("../data/constants").TScopeType} TScopeType */
/** @typedef {import("../data/constants").TLeaveRequestType} TLeaveRequestType */
/** @typedef {import("../data/constants").TLeaveRequestStatus} TLeaveRequestStatus */
/** @typedef {import("../data/constants").TLeaveRequestPurpose} TLeaveRequestPurpose */
/** @typedef {import("../data/constants").TInvoiceItemStatus} TInvoiceItemStatus */
/** @typedef {import("../data/constants").TFrozenBatchType} TFrozenBatchType */
/** @typedef {import("../data/constants").TTransactionMethod} TTransactionMethod */
