module.exports.NO_PARAMS = "Required body params or queries are missing";
module.exports.SERVER_ERROR = "Internal Server Error";
module.exports.NO_TOKEN = "Token is required";
module.exports.NO_FILE = "File is required";
module.exports.NO_ID_FOUND = "Required body params id is not found in the database.";
module.exports.DUPLICATE_KEY = "Required body params key is already exist";
module.exports.NO_DATA = "No Data";
module.exports.OWNER_ONLY_ACTION = "This action can only be completed by the resource's owner.";
module.exports.UNAUTHENTICATED = "You need to be authenticated to access this resource.";